/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui_laptopsales;

import javax.swing.ImageIcon;

/**
 *
 * @author megan
 */
public class ViewLaptops extends javax.swing.JFrame {

    /**
     * Creates new form ViewLaptops
     */
    public ViewLaptops() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbLaptop = new javax.swing.JComboBox<>();
        lblImg = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblName = new javax.swing.JLabel();
        lblMem = new javax.swing.JLabel();
        lblStor = new javax.swing.JLabel();
        lblPro = new javax.swing.JLabel();
        lblGraph = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("View Laptops:");

        cmbLaptop.setFont(new java.awt.Font("MS Gothic", 1, 10)); // NOI18N
        cmbLaptop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Acer Nitro", "Acer Predator", "Dell Inspirion", "HP Pavillion", "MSI Crosshair", "MSI Reaider", "Asus ROG Strix" }));
        cmbLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbLaptopActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Laptop Discription"));

        jLabel2.setText("Laptop Name:");

        jLabel3.setText("Memory:");

        jLabel4.setText("Storage:");

        jLabel5.setText("Processor:");

        jLabel6.setText("Graphics Card:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMem)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStor)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPro)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGraph)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cmbLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblImg, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLaptopActionPerformed
        if (cmbLaptop.getSelectedIndex() == 1){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\Acer Nitro 5 AN515-57.jpg");
            lblImg.setIcon(img);
            
            lblName.setText("Acer Nitro 15");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }else if(cmbLaptop.getSelectedIndex() == 2){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\Acer Predator Helios 500 .jpg");
            lblImg.setIcon(img);
            
            lblName.setText("Acer Predator Helios");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }else if(cmbLaptop.getSelectedIndex() == 3){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\Dell Inspiron 15 5515 AMD Ryzen.jpg");
            lblImg.setIcon(img);
            
            lblName.setText("Dell Inspirion 15");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }else if (cmbLaptop.getSelectedIndex() == 4){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\HP Pavilion Ryzen 5.jpg");
            lblImg.setIcon(img);
            
            lblName.setText("HP Pavillion");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }else if (cmbLaptop.getSelectedIndex() == 5){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\MSI Crosshair 15 Core.jpg");
            lblImg.setIcon(img);
            
            lblName.setText("MSI Crosshair 15");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }else if (cmbLaptop.getSelectedIndex() == 6){
            ImageIcon img = new ImageIcon("C:\\Users\\megan\\OneDrive\\Documents\\NetBeansProjects\\GUI_LaptopSales\\src\\gui_laptopsales\\Images\\MSI Raider GE76 i9 3080.jpg");
            lblImg.setIcon(img);
            
            lblName.setText("MSI Raider GE76");
            lblMem.setText("16 GB");
            lblStor.setText("1TB HDD");
            lblPro.setText("Intel Core i7 10th Gen");
            lblGraph.setText("NVIDIA® GeForce® RTX™ 3050Ti");
        }
    }//GEN-LAST:event_cmbLaptopActionPerformed

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        Welcome welc = new Welcome();
        welc.setVisible(true);
        
    }//GEN-LAST:event_btnBackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewLaptops.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLaptops().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbLaptop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblGraph;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblMem;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPro;
    private javax.swing.JLabel lblStor;
    // End of variables declaration//GEN-END:variables
}
